### ISSUE TITLE
Tag automatically updated releases

### ISSUE THREAD

**Issue by Helveg** [jpetrucciani/black-check#13]
The auto updater doesn't create tags, I'd like to check out a specific black version of this action, and now I've had to switch to using `master` to stay up to date; but I don't want to be THAT up to date 😇

**Comment by jpetrucciani** [comment]
That's a good point! I will take a look at this next week

**Comment by jpetrucciani** [comment]
Apologies for the delay here - this should now be included in the auto-update workflows!
