### ISSUE TITLE
Error upon running

### ISSUE THREAD

**Issue by Bobbyperson** [jpetrucciani/black-check#36]
```
+ black --version
black, 24.10.0 (compiled: no)
Python (CPython) 3.12.5
+ black --check .
Python 3.12.5 has a memory safety issue that can cause Black's AST safety checks to fail. Please upgrade to Python 3.12.6 or downgrade to Python 3.12.4
```

**Comment by NeerajG03** [comment]
Hey @jpetrucciani, this error seems to happen after the Dockerfile change.
I have raised a PR https://github.com/jpetrucciani/black-check/pull/37 
Could you take a look at this as this is really important in our CICD workflow

**Comment by jpetrucciani** [comment]
Merged - thanks for the PR!

**Comment by jpetrucciani** [comment]
also retagged [24.10.0](https://github.com/jpetrucciani/black-check/releases/tag/24.10.0) to include this
